<a href="https://colab.research.google.com/github/OussamaHaff/machine-learning-upskilling/blob/main/02-llms-from-scratch/04-token-embeddings-with-positional-encoding/token_embeddings_with_positisional_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic token IDs to embedding vectors

## Exploration

In [21]:
import torch

input_token_ids = torch.tensor([2, 3, 5, 1])

vocab_size = 6
output_embeddings_dim_size = 3

# Instantiate an embedding layer (with random seed 123 for reproducibility)
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(num_embeddings=vocab_size,
    embedding_dim=output_embeddings_dim_size)
print("Wights \n", embedding_layer.weight)
print("Shape\n", embedding_layer.weight.shape)

Wights 
 Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)
Shape
 torch.Size([6, 3])


In [18]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [19]:
print(embedding_layer(input_token_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


## Observations

- Initial Embedding weights are random.
- The Embedding layer is essentially a lookup function to get wights of of token IDs.