<a href="https://colab.research.google.com/github/OussamaHaff/machine-learning-upskilling/blob/main/02-llms-from-scratch/05-self-attention/simple_self_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple Self Attention Without Weights

## Input Embeddings

In [1]:
import torch

# Sentence: "Your journey starts with one step"
inputs = torch.tensor([
    [0.43, 0.15, 0.89], # Your
    [0.55, 0.87, 0.66], # journey
    [0.57, 0.85, 0.64], # starts
    [0.22, 0.58, 0.33], # with
    [0.77, 0.25, 0.10], # one
    [0.05, 0.80, 0.55], # step
])

print(inputs)

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])


## Calculating Attention Scores

# This is formatted as code




In [3]:
# [0.43, 0.15, 0.89]  [0.55, 0.87, 0.66]  [0.57, 0.85, 0.64]  [0.22, 0.58, 0.33]  [0.77, 0.25, 0.10]  [0.05, 0.80, 0.55]
#       Your           >>> journey <<<            starts              with               one              step
#                           query

# Attention weight for "journey"
journey_embedding_query_token = inputs[1]
print(f"Query token embeddings:\n", journey_embedding_query_token)

journey_attention_scores = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
  journey_attention_scores[i] = torch.dot(x_i, journey_embedding_query_token)

print(f"Self Attention scores for query:\n",journey_attention_scores)



Query token embeddings:
 tensor([0.5500, 0.8700, 0.6600])
Self Attention scores for query:
 tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


## Attention Scores Normalisation

### Basic Normalisation

In [4]:
# [0.43, 0.15, 0.89]  [0.55, 0.87, 0.66]  [0.57, 0.85, 0.64]  [0.22, 0.58, 0.33]  [0.77, 0.25, 0.10]  [0.05, 0.80, 0.55]
#       Your           >>> journey <<<            starts              with               one              step
#                           query
#
# Attentions Scores W_2T
#       0.9544             1.4950                 1.4754             0.8434             0.7070              1.0865

journey_attention_weights = journey_attention_scores / journey_attention_scores.sum()
print(f"Normalised self attention weights:\n", journey_attention_weights)
print(f"Normalised self attention weights sum:\n", journey_attention_weights.sum())

Normalised self attention weights:
 tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Normalised self attention weights sum:
 tensor(1.0000)


### Softmax Normalisation - Naive

In [5]:
# [0.43, 0.15, 0.89]  [0.55, 0.87, 0.66]  [0.57, 0.85, 0.64]  [0.22, 0.58, 0.33]  [0.77, 0.25, 0.10]  [0.05, 0.80, 0.55]
#       Your           >>> journey <<<            starts              with               one              step
#                           query
#
# Attentions Scores W_2T
#       0.9544             1.4950                 1.4754             0.8434             0.7070              1.0865
#
# Normalised Wights
#       0.1455             0.2278                  0.2249            0.1285             0.1077              0.1656

def softmax_naive(x):
  return torch.exp(x) / torch.exp(x).sum(dim=0)

journey_attention_weights_sfmx_nv = softmax_naive(journey_attention_scores)

print("Softmax Normalisation - Naive")
print(f"Normalised self attention weights:\n", journey_attention_weights_sfmx_nv)
print(f"Normalised self attention weights sum:\n", journey_attention_weights_sfmx_nv.sum())

Softmax Normalisation - Naive
Normalised self attention weights:
 tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Normalised self attention weights sum:
 tensor(1.)


### Softmax Normalisation - PyTorch (best)

In [6]:
# [0.43, 0.15, 0.89]  [0.55, 0.87, 0.66]  [0.57, 0.85, 0.64]  [0.22, 0.58, 0.33]  [0.77, 0.25, 0.10]  [0.05, 0.80, 0.55]
#       Your           >>> journey <<<            starts              with               one              step
#                           query
#
# Attentions Scores W_2T
#       0.9544             1.4950                 1.4754             0.8434             0.7070              1.0865
#
# Normalised Wights
#       0.1455             0.2278                  0.2249            0.1285             0.1077             0.1656
#
# Normalised Wights - Softmax Naive
#       0.1385             0.2379                  0.2333            0.1240             0.1082            0.1581


journey_attention_weights_sfmx = torch.softmax(journey_attention_scores, dim=0)
print("Softmax Normalisation - PyTorch")
print(f"Normalised self attention weights:\n", journey_attention_weights_sfmx)
print(f"Normalised self attention weights sum:\n", journey_attention_weights_sfmx.sum())

Softmax Normalisation - PyTorch
Normalised self attention weights:
 tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Normalised self attention weights sum:
 tensor(1.)


## Calculating Context Vector

In [8]:
# [0.43, 0.15, 0.89]  [0.55, 0.87, 0.66]  [0.57, 0.85, 0.64]  [0.22, 0.58, 0.33]  [0.77, 0.25, 0.10]  [0.05, 0.80, 0.55]
#       Your           >>> journey <<<            starts              with               one              step
#                           query
#
# Normalised Wights - Softmax PyTorch
#       0.1385              0.2379                  0.2333            0.1240            0.1082            0.1581


# Attention weight for "journey"
journey_embedding_query_token = inputs[1]
context_vector = torch.zeros(journey_embedding_query_token.shape)
for i, x_i in enumerate(inputs):
  context_vector += journey_attention_weights_sfmx[i]*x_i

print(context_vector)

tensor([0.4419, 0.6515, 0.5683])


### Calculating Context Vector of the full input

In [26]:
# [0.43, 0.15, 0.89]  [0.55, 0.87, 0.66]  [0.57, 0.85, 0.64]  [0.22, 0.58, 0.33]  [0.77, 0.25, 0.10]  [0.05, 0.80, 0.55]
#       Your                journey            starts              with                 one                  step

#
# inputs = torch.tensor([
#    [0.43, 0.15, 0.89], # Your
#    [0.55, 0.87, 0.66], # journey
#    [0.57, 0.85, 0.64], # starts
#    [0.22, 0.58, 0.33], # with
#    [0.77, 0.25, 0.10], # one
#    [0.05, 0.80, 0.55], # step
# ])


# For each token in the sentence we have 6 scores - sentence has 6 tokens
sentence_attention_scores = torch.zeros(6, 6)

print(f"sentence_attention_scores \n", sentence_attention_scores)
print(f"inputs \n", inputs)

for token_index, token_embeddings in enumerate(inputs):
  for context_index, context_embedding in enumerate(inputs):
    sentence_attention_scores[token_index, context_index] = torch.dot(token_embeddings, context_embedding)


print(f"sentence_attention_scores \n", sentence_attention_scores)


sentence_attention_scores 
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
inputs 
 tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])
sentence_attention_scores 
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [30]:
# The same could be acheived via matrix multiplication
sentence_attention_scores_matrix = inputs @ inputs.T

print(f"sentence_attention_scores_matrix \n", sentence_attention_scores_matrix)

sentence_attention_scores_matrix 
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [32]:
# Softmax to calculate weights from scors
# dim=-1 to apply the softmax based on the last dimention of the matrix - in this
# case it's a 2D matric, so it will apply on columns.
sentence_attention_weights = torch.softmax(sentence_attention_scores_matrix, dim=-1)

print(f"sentence_attention_weights \n", sentence_attention_weights)

sentence_attention_weights 
 tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [34]:
# Context Vectors
sentence_context_vectors = sentence_attention_weights @ inputs

print(f"sentence_context_vectors \n", sentence_context_vectors)

sentence_context_vectors 
 tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])
